export default {
  GET_CAMERAS: 'GET_CAMERAS',
  GET_CAMERAS_SUCCESS: 'GET_CAMERAS_SUCCESS',
  GET_CAMERAS_FAILURE: 'GET_CAMERAS_FAILURE',

  DELETE_CAMERA: 'DELETE_CAMERA',
  DELETE_CAMERA_SUCCESS: 'DELETE_CAMERA_SUCCESS',
  DELETE_CAMERA_FAILURE: 'DELETE_CAMERA_FAILURE',
  
  UPDATE_CAMERA_STATUS: 'UPDATE_CAMERA_STATUS',
}